FROM python:3.10-slim

WORKDIR /app

# Install Poetry
RUN pip install poetry==1.8.0

# Copy dependency files
COPY pyproject.toml ./

# Install dependencies (WITHOUT worker group)
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --without worker

# Copy application code
COPY . .

# NOTE: 是否統一讓 docker compose 去管理就好？
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
